dark-mode
Krystof-Bum/web-development-course pull request #2
Opened 2024-01-18 12:18 UTC by Krystof-Bum

2024-01-19 08:00 UTC, sdee3 requested changes

2024-01-19 08:00 UTC, sdee3 commented on flag-app/flag-app-project/src/DarkModeProvider.tsx
> +  const [mode, setMode] = React.useState<PaletteMode>("light");
Usually dark mode is persistent = "remembered" in the browser. Could you try implementing the Local Storage API for this feature?

2024-01-19 08:00 UTC, sdee3 commented on flag-app/flag-app-project/src/components/Card.tsx
> +        mode === "dark" ? "shadow-white" : ""
Two suggestions for making this look better:
https://www.npmjs.com/package/classnames
https://www.npmjs.com/package/tailwind-merge

Check their documentation to see what they help with.

2024-01-19 08:00 UTC, sdee3 commented on flag-app/flag-app-project/src/components/Filter.tsx
>    return (
I don't know if you have formatting disabled, but usually there should be an empty line above the `return` for better readability.

2024-01-19 08:00 UTC, sdee3 commented on flag-app/flag-app-project/src/components/Filter.tsx
> +          mode === "dark" ? "bg-darkModeBlack shadow-white" : "bg-white"
Same NPM package suggestion applies for this. It could look better

2024-01-19 08:00 UTC, sdee3 commented on flag-app/flag-app-project/src/components/Search.tsx
> +            mode === "dark" ? "bg-darkModeBlack" : "bg-white"
And also here and above L21-23

2024-01-19 08:00 UTC, sdee3 commented on flag-app/flag-app-project/src/context/darkModeContext.tsx
> +export const DarkModeContext = React.createContext<DarkModeContextType>({
The file name should match the main export, so `DarkModeContext.tsx` instead of `darkModeContext.tsx`

2024-01-19 08:00 UTC, sdee3 commented on flag-app/flag-app-project/src/main.tsx
> +import "./index.css";
One very important thing about this: always import CSS files **last**.  For better readability, you can add an empty line above this one:

```
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import DarkModeContextProvider from "./DarkModeProvider.tsx";

import "./index.css";
```

If at any point you import a CSS file above another React component, you could cause styling bugs and invalid UI rendering.

2024-01-21 18:35 UTC, Krystof-Bum commented on flag-app/flag-app-project/src/DarkModeProvider.tsx
> +  const [mode, setMode] = React.useState<PaletteMode>("light");
Good idea. I will add this on my "improvement" list and I will add that in the future

2024-01-21 18:41 UTC, Krystof-Bum commented on flag-app/flag-app-project/src/components/Card.tsx
> +        mode === "dark" ? "shadow-white" : ""
The same with this one

2024-01-21 18:44 UTC, merged